# Generated by Django 4.0.3 on 2022-04-02 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0002_remove_doctor_mobile_reception'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reception',
            new_name='Receptionist',
        ),
    ]
