# Generated by Django 4.0.3 on 2022-04-09 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_rename_reception_receptionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Patient Name')),
                ('email', models.EmailField(max_length=90, verbose_name='Email')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('contact', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, verbose_name='Gender')),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=10, verbose_name='Blood')),
            ],
        ),
    ]
