# Generated by Django 4.0.3 on 2022-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Patient'),
        ),
    ]
