# Generated by Django 4.0.3 on 2022-04-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_patient_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Prescription'),
        ),
    ]
